### ISSUE TITLE
 Could you tell me how to view the images generated by the model?

### ISSUE THREAD

**Issue by boxbox2** [sjtuplayer/anomalydiffusion#12]
In the "test_unet.py" , I only see the generation of masks, but I haven't found the generation of anomaly images. Can you tell me how to view the generated data?

**Comment by sjtuplayer** [comment]
You can just download the generated data from the [google drive](https://drive.google.com/file/d/1yzsZdW_xS-v4GprE2KQmQ1EbIWyGyFcG/view). And  "test_unet.py" is to test the anomaly detection accuracy rather than generating the anomaly images. If you want to generate anomaly data yourself, please wait for the inference code, which will be released this week.
