### ISSUE TITLE
Results on more datasets

### ISSUE THREAD

**Issue by DaiZhewei** [sjtuplayer/anomalydiffusion#63]
Hi author, 
I would like to ask if you can provide the results of your method on more datasets such as VisA, MVTec3D, MVTEC-LOCO or Real-IAD. thanks for the reply.

**Comment by sjtuplayer** [comment]
Sorry, there is no corresponding version. You may need to train it using the provided training code. By the way, This model may not perform well on the VisA dataset since the defects are too small and the generation size is limited for the currently employed stable diffusion model. But it is worth a try.
